### ISSUE TITLE
Translations not working when using 2.6 and Content Services

### ISSUE THREAD

**Issue by MariusGrunenberg** [Alfresco/generator-ng2-alfresco-app#167] opened 2018-10-17 07:19 UTC
I have the lastest Yeoman (2.5.0) and the latest adf-generator installed (also Node version 8.12.0).

However whenever I try to generate an app only content services, I don't see any translations. In my network tab however I see that the translation json files have been received.

Plus I get the error message "Uncaught ReferenceError: global is not defined"

I have tried it now on 2 different machines and both of them the same problem.

Steps to reproduce:

1. Install the versions mentioned above
2. yo alfresco-adf-app
3. Choose Content App
4. npm run start

**Comment by yregaieg** [comment] 2018-10-17 08:09
I have updated my generator using
```
$ npm install -g generator-alfresco-adf-app
```

and I confirm I can still see the same issue in ADF 2.6.0 and latest alpha

**Comment by DenysVuika** [comment] 2018-10-17 08:12
What is the system/browser locales when app runs?

**Comment by yregaieg** [comment] 2018-10-17 08:14
In my case, I did set my chrome browser to prefere french/France

**Comment by MariusGrunenberg** [comment] 2018-10-17 08:17
German for me

**Comment by yregaieg** [comment] 2018-10-17 08:55
Following the discussion on gitter, and my own local experiments, I think the issue to be a race condition : if the language/locale gets set before/after the assets has been loaded, and depending on that you might or not experience the bug.
But I can confirm it is still present in latest Alpha at the time of writing

**Comment by DenysVuika** [comment] 2018-10-17 08:56
Thanks @MariusGrunenberg and @yregaieg. We will try to reproduce this locally.

**Comment by eromano** [comment] 2018-10-17 09:03
guys can you please create a repo with your problem? I am not able to reproduce it locally

**Comment by yregaieg** [comment] 2018-10-17 09:10
@eromano I just pushed the project I was testing on to https://github.com/yregaieg/adf-i18n-issue-167

**Comment by eromano** [comment] 2019-02-21 12:26
this problem seems to be ok in 3.0.0 i close the issue

**Closed by eromano** 2019-02-21 12:26 UTC
