### ISSUE TITLE
errors during app startup

### ISSUE THREAD

**Issue by romainguinot** [Alfresco/generator-ng2-alfresco-app#66] opened 2017-02-07 16:35 UTC
App starts with the errors, but these errors appear : 

npm ERR! peer dep missing: @angular/core@~2.0.0, required by ng2-translate@2.5.0
npm ERR! peer dep missing: @angular/core@~2.0.0, required by ng2-translate@2.5.0
npm ERR! peer dep missing: @angular/http@~2.0.0, required by ng2-translate@2.5.0
npm ERR! peer dep missing: @angular/http@~2.0.0, required by ng2-translate@2.5.0
npm ERR! peer dep missing: zone.js@^0.6.21, required by @angular/core@2.2.2

ADF 1.1. standard default app generated by the hipster yeoman tool : yo ng2-alfresco-app

Are these expected or not ? 

Please advise, 
Thanks.

**Comment by ohej** [comment] 2017-02-07 16:37
Closing as a duplicate of this: https://github.com/Alfresco/alfresco-ng2-components/issues/1397

**Comment by ohej** [comment] 2017-02-07 16:37
Sorry, I forgot to add: The errors can safely be ignored

**Closed by ohej** 2017-02-07 16:37 UTC

**Comment by romainguinot** [comment] 2017-02-08 13:33
@ohej Hi Ole, there is an additional error in my case that from the duplicate. The zone.js dependency. 

Can that one be ignored as well ?

**Comment by eromano** [comment] 2017-02-08 13:46
Hi @romainguinot Yes you can it is a install warning and is due to the verbose npm report.
